name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        - stable
        - 1.31.1 # MSRV (Rust 2018)

    steps:
    - uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Run cargo build w/ serde
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --features serde

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Run cargo test w/ serde
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features serde

#     - name: Build
#       run: cargo build --verbose
#     - name: Build (serde)
#       run: cargo build --verbose --features serde
#     - name: Run tests
#       run: cargo test --verbose
#     - name: Run tests (serde)
#       run: cargo test --verbose --features serde
